blank_issues_enabled: false
contact_links:
  - name: â” Frequently asked questions
    url: https://klmr.me/box/articles/faq.html
    about: The â€˜boxâ€™ website contains a list of frequently asked questions
  - name: ğŸ’¬ â€˜boxâ€™ questions on Stack Overflow
    url: https://stackoverflow.com/questions/tagged/r-box?sort=Newest
    about: When asking questions about â€˜boxâ€™ on Stack Overflow, please use the [r-box] tag
  - name: ğŸ’¬ General questions and discussions
    url: https://github.com/klmr/box/discussions/categories/q-a
    about: You can also use the GitHub Discussions board for questions and answers
